### ISSUE TITLE
Handle new TLDs

### ISSUE THREAD

**Issue by fser** [AlternC/AlternC#119]
I wanted to add a `.party` domain, which is not handled by AlternC, because of the whois lookup. Maybe we should use a third party library to implement the whois, or use the system command.
This would avoid tedious parsing of the whois output.

**Comment by innoticFR** [comment]
You should see #95 (which seems to be a duplicate)

The proposed behavior is to allow any domain by default, and test DNS server name registered from the authoritative server of the TLD. Exceptions for AFNIC-like registry where the domain is expected to be installed on the server first

**Comment by fser** [comment]
Right my bad. I've been talking about that on IRC, and nobody told me about this issue. Nevertheless, DNS lookup and whois lookup are not exactly the same.

Anyhow, we've got to decide something.

**Comment by vincib** [comment]
Also, sometimes (most of the time?) you'd want to DNS-host a domain BEFORE moving it to your server, because some TLD check that (using zonecheck or http://www.zonemaster.fr/ ) 
So, I guess that removing the TLD check altogether seems to be the way to go (to me at least) 

The only reason we did that were in case someone pretended to host "gmail.com" or "yahoo.co.uk" in your server, preventing you to SEND emails to those domains because postfix would think they were locally hosted.

the domain blacklist is here for that reason, and even if it's not perfect, I guess it's fine.

**Comment by innoticFR** [comment]
There are other options used by other DNS providers, for instance adding a file/dns record on the domain to prove we are owner of the domain. 

So, if the domain does not exist : we can add without any check
If the domain do exist, make some check like adding a random subdomain (ekezrkjez-alternc.example.com, or random txt file on the main domain (ekezrkjez-alternc.txt containing ekezrkjez-alternc).

**Comment by vincib** [comment]
Closed, see #195 for a formal evolution proposal
