### ISSUE TITLE
Right user on phpmyadmin (apache process)

### ISSUE THREAD

**Issue by camlafit** [AlternC/AlternC#139]
I've get some error with phpmyadmin. Seen in error.log as : 
`phpmyadmin: Failed to load /etc/phpmyadmin/config-db.php. Check group www-data has read access., referer: `

Looks related also to #84 

To solve my problem, I've update `/etc/apache2/conf.d/phpmyadmin.conf` with theses rule in `<Directory /usr/share/phpmyadmin>` part :
```
        AssignUserId #33 #33
        SetEnv LOGIN "33-www-data"
```

**Comment by innoticFR** [comment]
I cannot see this problem under a Jessie installation.

The phpmyadmin.conf is the default phpmyadmin configuration

AlternC already specifies the configuration for phpmyadmin in `/etc/alternc/apache2.conf` and `/etc/alternc/bureau.conf` 

We can ignore/remove the default phpmyadmin configuration.

The `/alternc-sql/` url is called with the "alterncpanel" group and user

**Comment by camlafit** [comment]
To follow #84, why would be set aterncpanel as user, and not to www-data.
In this case phpmyadmin is not related to alternc management, then looks be to set as normal www user.

**Comment by vincib** [comment]
- we need to run phpmyadmin as alterncpanel, not www-data, since it's in the same vhost as the panel. (itk can't separate unix user per directory) 
- so the bureau.conf has all the necessary stuff to make it work, we don't need /etc/apache2/conf-enabled/phpmyadmin.conf
- BUT we need to have /etc/phpmyadmin/* accessible to alterncpanel user (this is ensured in alternc.install)
