### ISSUE TITLE
Stockage de hashes de mots de passe

### ISSUE THREAD

**Issue by lelutin** [AlternC/AlternC#227]
Ça fait déjà un bail que j'ai remarqué que l'utilisation de MD5 persiste dans AlternC (je crois qu'il y avait un billet dans trac mais il n'a pas suivi la migration à github).

Il serait plus que temps de se débarrasser de MD5 pour le stockage de hashes de mots de passe.

Les endroits que je connais qui utilisent toujours MD5:

 * le login des comptes alternc -- il n'y a pas de bonne raison de rester derrière
 * les mots de passe de boîtes de courriels -- dovecot est capable d'utiliser des algorithmes plus récent maintenant
 * les users ftp (même pas de salt!!)

Donc ça serait bien de penser à changer à qqch de plus moderne comme par exemple bcrypt

Il faudra également supporter les vieux mdp MD5 pendant un bout de temps, et trouver un moyen pour encourager les utilisateurs/trices à changer leur mot de passe pour que celui-ci passe au nouvel algo de hashage.

**Comment by camlafit** [comment]
Hello

I don't remember how we do. But could be interesting to have a specific method to crypt password and use it where is required.
Then we could use any crypt solution and provide an automatic failback

Can you prepare a PR ? :)

**Comment by kienanstewart** [comment]
I started working on this: https://github.com/kienanstewart/AlternC/tree/issue-227-password_hashes

Currently only changes for member accounts.

**Comment by kienanstewart** [comment]
I've made the following changes: user accounts use bcrypt and dovecot/ftpusers use sha512-crypt with 20000 rounds (not configurable currently)

No changes should be needed to dovecot/proftpd since they support methods for deciding on the hash routine and salt based on the stored value.

I tested with doveadm auth, and directly against proftp. I think roundcube / smtpd / imap / pop should be fully tested since I'm not sure if configuration changes are required for any of those services.

User login provides a transition path to update from md5 based hash to bcrypt. No transition is in place for dovecot or ftpusers. Previous set passwords continue to work in all cases.

**Comment by kienanstewart** [comment]
Also I should note that the changes break compatibility with php versions before 5.5 and doesn't supply patches to continue support for wheezy and earlier at this point.

**Comment by camlafit** [comment]
Hello

From July 2018, we'll stop wheezy support. We've planed an alternc camp to Paris in June, we'll close old support. normally :) 
In this case, theses modification could be merge at this moment.

Could you propose as PR, should be easier to follow your change.

Thanks a lot :)
