### ISSUE TITLE
Filemanager

### ISSUE THREAD

**Issue by hostquota** [AlternC/AlternC#267]
Just a suggestion: Alternc's filemanager let's it down because you can only upload 2m files and cannot upload zipped/compressed folders. It would be great if you could.

**Comment by vincib** [comment]
- we added a patch in 3.5.0~rc1 to allow up to 200MB large files
- ZIP, tgz, tbz and other .tar.z are supported since lonnnnng (like... 2005? ;)). To use it : upload a zip file, and once it's there, click the "expand" link next to the filename. (I added a message telling this to the user below the upload form.

**Comment by vincib** [comment]
f166518b
