### ISSUE TITLE
[Legacy] Should we keep squirrelmail?

### ISSUE THREAD

**Issue by fser** [AlternC/AlternC#316]
All in title

**Comment by lelutin** [comment]
Just dropping info that I know about squirrelmail here:

The webmail's debian package was removed from archives since stretch (last version present is in jessie):

https://packages.debian.org/jessie/squirrelmail

the last upstream realease was in may 2013, so around 5.5 years ago, and its goal was to add PHP 5.4 and 5.5 compatibility. I presume it won't handle the upgrade to 7.x too well:

https://www.squirrelmail.org/index.php

**Comment by lelutin** [comment]
there still seems to be movement in the repository

https://sourceforge.net/p/squirrelmail/code/HEAD/tree/

but no release for a long while

**Comment by ddeenniiss** [comment]
Plus de release depuis des années, plus dans debian ...
