### ISSUE TITLE
"Whitescreen" when using the filebrowser in directories which are not empty

### ISSUE THREAD

**Issue by kienanstewart** [AlternC/AlternC#402]
There seems to be a problem with the filebrowser, where are whitescreen is shown when navigating to directories which are not empty.

To reproduce:

 1. install alternc
 2. login
 3. click on filebrowser in the left hand side menu

The page will load (and in fact, the interface will be briefly visible), but then it's hidden underneath something else.

**Comment by kienanstewart** [comment]
I've worked around this issue temporarily by deactivating some of the on-load javascript: ```
diff --git a/bureau/admin/bro_main.php b/bureau/admin/bro_main.php
index afad4b66..53b01b87 100755
--- a/bureau/admin/bro_main.php
+++ b/bureau/admin/bro_main.php
@@ -682,6 +682,7 @@ else {
 </td></tr></table>
 
 <script type="text/javascript">
+/*
 $(document).ready(function() {
   $("#tab_files_w_details").tablesorter({
     textExtraction: function(node) {
@@ -693,6 +694,7 @@ $(document).ready(function() {
     } 
    });
 }); 
+ */
 </script>
 
 <?php include_once("foot.php"); ?>
```

I'm not yet sure of the actual cause of the problem.

**Comment by ulvida** [comment]
This problem only happens with debian buster, not with stretch. 
By the way, its not clear neither what does the javascript code you commented.

**Comment by albancrommer** [comment]
I have confirmed that rolling back the package `libjs-jquery-tablesorter` to stretch version is a dirty way to fix the problem.

Yet the plugin is working well in other pages, so it has to be something with the code

This one page and table has a javascript script generating the "Check All" button located in the THEAD's first TH :

```
          <tr><th>
          <script type="text/javascript">
          <!--
          document.write("<input type=\"checkbox\" id=\"checkall\" value=\"1\" class=\"inb\" onclick=\"CheckAll();\" />");
        //  -->
        </script>
          </th>
```
This causes the plugin to erase a page and fill it with only that checkbox...

The fix is simple: add the input in a plain and simple way.
