### ISSUE TITLE
Do not use MD5 for password hashing

### ISSUE THREAD

**Issue by N07070** [AlternC/AlternC#456]
Hello, 

While looking through the code to find an issue with password changes, I saw that you where using MD5 to hash a password.

It is seen as bad practice, and does not make for secure hashing. The use of a salt mitigates this, but new and better hashing algorithms can be used to improve the security of the compromised data, in case a leak happens.

https://github.com/AlternC/AlternC/blob/9fe5164405e8250aa60c8a482862942677907e2c/squirrelmail/alternc_changepass/change.php#L15

Please see more :
-  https://security.stackexchange.com/questions/19906/is-md5-considered-insecure
- https://robinverton.de/blog/2012/07/15/cracking-salted-md5-with-hashcat/

**Comment by camlafit** [comment]
Hello

Thanks for your issue. Meantime we'll check how to optimize this part, we're open to get any PR about this.

Thanks

**Comment by lelutin** [comment]
Hi! thanks @N07070  this is indeed important. there was similar work done and merged on master a while ago for other passwords: #235

For what it's worth, squirrelmail has not seen any releases for seven years, https://squirrelmail.org/, so I would recommend against using this software. However, AlternC has yet to cut out support for this software.

The previously-mentioned pull request changed the hashing algorithm used for email passwords when changed through AlternC's web interface (and also through AlternC's API since it ends up using the same code path):

https://github.com/AlternC/AlternC/blob/9fe5164405e8250aa60c8a482862942677907e2c/bureau/class/functions.php#L1239

However, it would seem as though roundcube's password plugin configuration imposed by AlternC still uses md5, which should also receive some attention:

https://github.com/AlternC/AlternC/blob/master/roundcube/templates/roundcube/plugins/password/config.inc.php#L73

so I'd suggest we change both squirrelmail's configuration and roundcube's until AlternC officially decides to stop supporting squirrelmail

**Comment by vincib** [comment]
This brings to our attention the discussion we may need to have about the hash algorithm choice...

**Comment by vincib** [comment]
Sooo... It has been fixed in 2018 but since we didn't release an official stable since then, some AlternC still have the md5 hash.
cf PR https://github.com/AlternC/AlternC/pull/235

I'll close this one then. Thanks !
