### ISSUE TITLE
Unable to logout when logging in to the panel using /main.php?http_auth=1

### ISSUE THREAD

**Issue by anthonygkk** [AlternC/AlternC#5]
1. Updated /usr/share/alternc/panel/admin/index.php and included the following:
<?php header("Location: /main.php?http_auth=1"); exit();

2. User is able to login with the pop-up form generated by Apache. Username and password is derived from the AlternC members database

3. After clicking on logout at the AlternC panel and immediately refreshing the browser, the session is still valid which means that user is still logged in

**Comment by lelutin** [comment]
Hi there,

If I understand what you're doing corretly, then it might be hard to implement logout consistently since basic authentication logins are cached in the browser.

You might be interested by the "security" section of the following page:

https://en.wikipedia.org/wiki/Basic_access_authentication

**Comment by vincib** [comment]
yes, using HTTP auth makes it *impossible* to log out properly in a portable way.

That's why we chose php/cookie/form auth at the beginning of the project, in 2001 ;) 

We provide AlternC user with a "http auth mode" just for compatibility with other applications like LemonLdap, but that's clearly a corner-case for people who like tinkering with software. I don't recommend using it.
