### ISSUE TITLE
[crash] upgrade alternc 1 to 3.1.8 or 3.1.8 to 3.2.8

### ISSUE THREAD

**Issue by skhaen** [AlternC/AlternC#6]
I want to update an alternc from v1 to v3.1.8 on a debian squeeze : 

```
Paramétrage de alternc (3.1.8) ...
quota: Mountpoint (or device) / not found or has no quota enabled.
quota: Les points de montage spécifiés n'utilisent pas tous les quotas.
dpkg-statoverride: Une dérogation pour « /var/spool/postfix/var/run/saslauthd » existe déjà, Abandon.
vmail:x:1998:
vmail:x:1998:1998::/var/alternc/mail:/bin/sh
Updating /etc/alternc/local.sh
Granting users...
Trying debian.cnf: ok!
Updating mysql configuration in /etc/alternc/my.cnf
Updating mysql configuration in /etc/alternc/my_mail.cnf
Checking for MySQL connectivity
MYSQL.SH OK!
installing AlternC schema in alternc...

ERROR 1050 (42S01) at line 388: Table 'variable' already exists
cannot load database schema
ERROR 1142 (42000) at line 1: GRANT command denied to user 'sysusr'@'localhost' for table 'dovecot_view'

dpkg : erreur de traitement de alternc (--configure) :
 le sous-processus script post-installation installé a retourné une erreur de sortie d'état 1
configured to not write apport reports
                                      Des erreurs ont été rencontrées pendant l'exécution :
 alternc
E: Sub-process /usr/bin/dpkg returned an error code (1)
```
The problem appears in the `/usr/share/alternc/install/mysql.sh` file:

```
$mysql <<EOF
$grant_mail
EOF    
```

if i delete this, it's run smoothly

**Comment by skhaen** [comment]
same thing from squeeze/alternc 3.1.8 to wheezy/alternc 3.2.8

**Comment by lelutin** [comment]
hey there,

On 20/08/15 10:14 AM, Skhaen wrote:
> I want to update an alternc from v1 to v3.1.8 on a debian squeeze :
> 
> |Paramétrage de alternc (3.1.8) ... quota: Mountpoint (or device) / not
> found or has no quota enabled. quota: Les points de montage spécifiés
> n'utilisent pas tous les quotas. dpkg-statoverride: Une dérogation pour
> « /var/spool/postfix/var/run/saslauthd » existe déjà, Abandon.
> vmail:x:1998: vmail:x:1998:1998::/var/alternc/mail:/bin/sh Updating
> /etc/alternc/local.sh Granting users... Trying debian.cnf: ok! Updating
> mysql configuration in /etc/alternc/my.cnf Updating mysql configuration
> in /etc/alternc/my_mail.cnf Checking for MySQL connectivity MYSQL.SH OK!
> installing AlternC schema in alternc... ERROR 1050 (42S01) at line 388:
> Table 'variable' already exists cannot load database schema ERROR 1142
> (42000) at line 1: GRANT command denied to user 'sysusr'@'localhost' for
> table 'dovecot_view' dpkg : erreur de traitement de alternc
> (--configure) : le sous-processus script post-installation installé a
> retourné une erreur de sortie d'état 1 configured to not write apport
> reports Des erreurs ont été rencontrées pendant l'exécution : alternc E:
> Sub-process /usr/bin/dpkg returned an error code (1) |
> 
> The problem appears in the |/usr/share/alternc/install/mysql.sh| file:
> 
> |$mysql <<EOF $grant_mail EOF |
> 
> if i delete this, it's run smoothly

if I'm not mistaken the mysql.sh script only errors out because the last
command that's run (the block of code you quoted just above) returns a
non-0 code.
there's no set -e to make the script exit upon first encoutered error,
and actually there's no error handling at all in that script.

a very dirty hack might be to add a line at the end of the script:

exit 0

but I doubt that the authors intended to just disregard errors like that.
best thing would be to figure out why you're getting that error in the
first place.


if you run the grant line manually (defined on lines 59 and 60 of
install/mysql.sh) with the sysuser user, do you get a permission denied
error?

-- 
Gabriel Filion

**Comment by vincib** [comment]
LeLutin, "Trying debian.cnf: ok!" me fait dire que ton /etc/mysql/debian.cnf n'a pas le droit de faire des GRANT sur les bases. ce n'est pas normal, peux-tu vérifier cela ?

**Comment by lelutin** [comment]
@vincib j'ai simplement fourré mon nez dans un billet qui était ouvert.. je renvois donc ta question à @skhaen 

@skhaen, since your issues are usually in english I'll translate @vincib 's question: the message "Trying debian.cnf: ok!" gives the idea that the credentials in your /etc/mysql/debian.cnf file don't have access to running GRANT which is not normal. Could you verify if this is the case (maybe by trying to run a similar GRANT manually)?
